# Generated by Django 5.2.10 on 2026-01-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reelinsight_audio_drive_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reelinsight',
            name='audio_drive_url',
        ),
        migrations.RemoveField(
            model_name='reelinsight',
            name='video_drive_url',
        ),
    ]
