"""Migration to rename transcript fields and add originals."""

# Generated by Django 5.2.10 on 2026-01-11 15:07
# pylint: disable=invalid-name
from django.db import migrations, models


class Migration(migrations.Migration):
    """Rename transcript fields and add the original transcript."""

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="reelinsight",
            old_name="transcript",
            new_name="transcript_english",
        ),
        migrations.AddField(
            model_name="reelinsight",
            name="transcript_original",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reelinsight",
            name="id",
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
