# Generated by Django 5.2.10 on 2026-01-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_transcript_reelinsight_transcript_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelinsight',
            name='audio_drive_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reelinsight',
            name='video_drive_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reelinsight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reelinsight',
            name='transcript_original',
            field=models.TextField(),
        ),
    ]
