# Generated by Django 5.2.10 on 2026-01-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reelinsight_audio_drive_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelinsight',
            name='audio_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reelinsight',
            name='original_language',
            field=models.CharField(max_length=10),
        ),
    ]
