# Generated by Django 6.0.2 on 2026-02-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reelinsight_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelinsight',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
