# Generated by Django 6.0.2 on 2026-02-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reelinsight_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelinsight',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
